config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ingredients
  root to: 'recipes#searchbyingt'
  resources :recipes do 
  	collection do 
  		get :searchbyingt
  	end
  	collection do 
  		get :searchbyrecipe
  	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

     if user.chef?
        can :manage, Recipe, user_id: user.id
        can :manage, Ingredient
        else
            can :read, Recipe
            can :read, Ingredient
        end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_and_belongs_to_many :recipes

	validates_presence_of :name
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_and_belongs_to_many :ingredients
	belongs_to :user
	
	validates_presence_of :user
	validates_presence_of :title
	validates_presence_of :prep
	validates_presence_of :preptime
	validates_presence_of :serving
	validates_presence_of :user_id

	mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

   protected

       def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name])


         end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:searchbyingt, :searchbyrecipe, :index]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    # @recipes = Recipe.accessible_by(current_ability)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
     @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.ingredients
  end
#search by ingredients
  def searchbyingt
     @ingredients = Ingredient.all
    if params[:ingredient_ids]      
        @recipes = Ingredient.where(id: params[:ingredient_ids]).map{ |ing| ing.recipes }.flatten.uniq
    else
        @recipes = Recipe.all
    end  
  end
  
#search by Recipe title 
  def searchbyrecipe 
    @recipes = if params[:title]
  	  Recipe.where('title like?', "%#{params[:title]}%")
    else
      Recipe.all
    end
  end

  # GET /recipes/new
  def new
   @recipe = Recipe.new
    @ingredients = Ingredient.all
  end

  # GET /recipes/1/edit
  def edit
    @ingredients = Ingredient.all
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    authorize! :create, @recipe

     params[:recipe][:ingredient_ids].each do |ingredient_id|
      unless ingredient_id.empty?
        ingredient = Ingredient.find(ingredient_id)
        @recipe.ingredients << ingredient
      end
    end

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    authorize! :update, @recipe
    params[:recipe][:ingredient_ids].each do |ingredient_id|
      unless ingredient_id.empty?
        ingredient = Ingredient.find(ingredient_id)
        @recipe.ingredients << ingredient
      end
    end
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    authorize! :destroy, @recipe
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :prep, :preptime, :serving, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<div class="jumbotron">
  <div class="container">

<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, class:"form-control form-control-sm ml-3 w-50", placeholder:"Ingredient name..." %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-light btn-block" %>
  </div>
<% end %>
</div>
</div>

app/views/ingredients/edit.html.erb
<div class="jumbotron">
  <div class="container">

<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>
</div>
</div>

app/views/ingredients/index.html.erb
<div class="jumbotron">
  <div class="container">

<p id="notice"><%= notice %></p>


<h6>
<%= link_to 'New Ingredient', new_ingredient_path, class:"fa fa-plus-circle fa-lg cyan-text" %>
</h6>
</br>
<table class="table ">

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr >
        <td><strong><%= link_to ingredient.name, ingredient_path(ingredient) %></strong></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Delete', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

app/views/ingredients/new.html.erb
<div class="jumbotron">
  <div class="container">

<%= render 'form', ingredient: @ingredient %>

</div>
</div>

app/views/ingredients/show.html.erb
<div class="jumbotron">
  <div class="container">
  	
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfridgerecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header >

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark blue lighten-4">

    <a class="navbar-brand" href="#"><%= link_to "Home", root_path, class: "navbar-brand" %></a>
      
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
     </button>

  <!-- Collapsible content -->
     <div class="collapse navbar-collapse" id="basicExampleNav">

        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">

            <% if (signed_in? && current_user.chef) == true %>
                
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Manage recipes
                      </a>
                      <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink">
                        <%= link_to 'New Recipe', new_recipe_path, class:"dropdown-item" %>

                        <%= link_to 'Manage ingredients', ingredients_path, class:"dropdown-item" %>
                      </div>
                </li>
                    
                  <span class="sr-only">(current)</span>

               
            <% end %>
              <span class="sr-only">(current)</span>
          </li>

           <% if signed_in? %>

          <li class="nav-item">
             <%= link_to "Recipes", recipes_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
             <%= link_to "Search by recipe", searchbyrecipe_recipes_path, class:"nav-link" %>
          </li>

            <li class="nav-item dropdown">

              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Profile
              </a>
              <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">

                <%= link_to current_user.name , edit_user_registration_path, class:"dropdown-item" %>     
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %>

              </div>

          </li>
          
        <% else %>

          <li class="nav-item">
             <%= link_to "Recipes", recipes_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
             <%= link_to "Search by recipe", searchbyrecipe_recipes_path, class:"nav-link" %>
          </li>

          </ul>
    </div>

          
<ul class="navbar-nav ml-auto">
            <li class="nav-item ">
                <%= link_to "Log in", new_user_session_path, class:"nav-link" %>
          </li>
        </ul>
      </div>
</div>
        <% end %>


  </nav>
</header>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="jumbotron">
  <div class="container">

<form class="form-inline d-flex justify-content-center md-form form-sm active-cyan active-cyan-2 mt-2">
   
  <input class="form-control form-control-sm ml-3 w-75" placeholder="Enter ingredients" 
    aria-label="Search" data-toggle="modal" data-target="#basicExampleModal">
  </form>

<!-- Modal -->
<div class="modal fade left" id="basicExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-full-height modal-left" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title w-100 font-weight-bold"  id="myModalLabel">Ingredients</h4>
      </div>

      <div class="modal-body">
        <p>
            
            <% @ingredients.each do |ingredient| %>
            <label>
            <%= check_box_tag "recipe[ingredient_ids][]", ingredient.id, @recipe.ingredients.include?(ingredient) %>
            <%= ingredient.name %>
            </label>  
           <% end %>
       </p>
       <button type="button" class="btn btn-link btn-lg btn-block" data-dismiss="modal" aria-label="Close">Done</button>
      </div>    
    </div>

</div>
</div>

</br>

  
   <div class="form-group">
    <%= form.text_field :title, class:"form-control form-control-sm ml-3 w-75", placeholder:"Title..."  %>
  </div>

  
  <div class="form-group">
    <%= form.text_area :prep, :rows=>8, class:"form-control form-control-sm ml-3 w-75", placeholder:"Preparation" %>
  </div>

  
   <div class="form-group">
    <%= form.text_field :preptime, class:"form-control form-control-sm ml-3 w-75", placeholder:"Time" %>
  </div>

 
   <div class="form-group">
    <%= form.number_field :serving, class:"form-control form-control-sm ml-3 w-75", placeholder:"Serving" %>
  </div>

  <div class="form-group">
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-light btn-block" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="jumbotron">
  <div class="container">

  	<div class="panel panel-info">

	 	<div class="panel-heading">
			<h2><strong>Editing Recipe:</strong></h2>
		</div>

		<div class="panel-body">
			<%= render 'form', recipe: @recipe %>
			<%= link_to 'Show', @recipe %> |
			<%= link_to 'Back', recipes_path %>
		</div>

	</div>

  </div>
</div>

app/views/recipes/index.html.erb
<div class="jumbotron">
  <div class="container">

<p id="notice"><%= notice %></p>

<div class="row row-cols-1 row-cols-md-3">
<% @recipes.each do |recipe| %>

  <div class="col mb-4">
<div class="card">
   <!--Card image-->
    <% if (recipe.image.small_thumb.url)  %>
         <%= link_to(image_tag(recipe.image.small_thumb.url), recipe, class:"view overlay") %>

      <% else %>

        <%= link_to(image_tag('https://mdbootstrap.com/img/Photos/Lightbox/Thumbnail/img%20(147).jpg', class:"card-img-top"), recipe, class:"view overlay") %>
     
      <% end %>
       
          <div class="mask rgba-white-slight"></div>
     
      <div class="card-body">
        <!--Title-->
        <h5 class="card-title"><%= link_to recipe.title, recipe %></h5>
        <!--Text-->
        <div class="a"><%= recipe.prep %></div>

        

      </div>
    </div>
</div>
  <% end %>

</div>
</div>

app/views/recipes/new.html.erb
<div class="jumbotron">
	    <div class="container">

		  	<div class="panel panel-info">

				<div class="panel-body">
					<%= render 'form', recipe: @recipe %>
				</div>

			</div>

  	    </div>
</div>

app/views/recipes/searchbyingt.html.erb
<div class="jumbotron">
  <div class="container">

<!-- Button trigger modal -->
<form class="form-inline d-flex justify-content-center md-form form-sm active-cyan active-cyan-2 mt-2">
  
  <i class="fa fa-search" aria-hidden="true"></i>
  <input class="form-control form-control-sm ml-3 w-75" placeholder="Search by ingredient " 
    aria-label="Search" data-toggle="modal" data-target="#basicExampleModal">
  </form>

</br>
</br>
<!-- Modal -->
<div class="modal fade left" id="basicExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-full-height modal-left" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title w-100 font-weight-bold"  id="myModalLabel">Ingredients</h4>
      </div>

      <div class="modal-body">
        <p>
            <%= form_tag(searchbyingt_recipes_path, :method => "get") do %> 
            <% @ingredients.each do |ingredient| %>
            <label>
             <%= check_box_tag 'ingredient_ids[]', ingredient.id -%>
             <%= ingredient.name-%>
           </label>
            <% end %>
       </p>
      </div>

        <%= submit_tag ("Search"), class:"btn btn-link btn-lg btn-block" %>
        <% end %>
    
    </div>
  </div>
</div>


<p id="notice"><%= notice %></p>

<div class="row row-cols-1 row-cols-md-3">
<% @recipes.each do |recipe| %>
<div class="col mb-4">
<div class="card">
   <!--Card image-->

   <% if (recipe.image.small_thumb.url)  %>
     <%= link_to(image_tag(recipe.image.small_thumb.url), recipe, class:"view overlay") %>

     <% else %>
       
        <%= link_to(image_tag('https://mdbootstrap.com/img/Photos/Lightbox/Thumbnail/img%20(147).jpg', class:"card-img-top"), recipe, class:"view overlay")%>
     
      <% end %>

      <div class="mask rgba-white-slight"></div>
     
        <div class="card-body">
          <!--Title-->
          <h5 class="card-title"><%= link_to recipe.title, recipe %></h5>
          <!--Text-->
          <div class="a"><%= recipe.prep %></div>

        </div>
    </div>
</div>

  <% end %>

</div>
</div>
</div>

app/views/recipes/searchbyrecipe.html.erb
<div class="jumbotron">
  <div class="container">



<div class="search">
<%= form_tag(searchbyrecipe_recipes_path, :method => "get", class:"form-inline d-flex justify-content-center md-form form-sm active-cyan active-cyan-2 mt-2") do %> 
<i class="fa fa-search" aria-hidden="true"></i>
<%= text_field_tag(:title,nil, class:"form-control form-control-sm ml-3 w-75", placeholder:"Search by recipe") %>
<% end %>

</div>
</br>
</br>
<p id="notice"><%= notice %></p>
<div class="row row-cols-1 row-cols-md-3">

<% @recipes.each do |recipe| %>

 <div class="col mb-4">
<div class="card">
   <!--Card image-->
    <% if (recipe.image.small_thumb.url)  %>
       <%= link_to(image_tag(recipe.image.small_thumb.url), recipe, class:"view overlay") %>

      <% else %>
      
       <%= link_to(image_tag('https://mdbootstrap.com/img/Photos/Lightbox/Thumbnail/img%20(147).jpg', class:"card-img-top"), recipe, class:"view overlay")%>
     
      <% end %>
       
      <div class="mask rgba-white-slight"></div>
     
        <div class="card-body">
          <!--Title-->
          <h5 class="card-title"><%= link_to recipe.title, recipe %></h5>
          <!--Text-->
          <div class="a"><%= recipe.prep %></div>
        </div>
    </div>
</div>

  <% end %>


</div>
</div>

app/views/recipes/show.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="panel panel-default">
        <div class="panel-body">

            <div class="center">

              <p id="notice"><%= notice %></p>
              </br>

              <div class="content">
                <br />

                <div class="row">
                  <div class="col"></div>

                  <div class="col">
                        
                        <% if @recipe.image? %>

                       <%= image_tag(@recipe.image.thumb.url, alt: 'Image') %>
                        </div>

                    <div class="col-md-6">

                       <% else %>
                        <img  src="https://mdbootstrap.com/img/Photos/Lightbox/Thumbnail/img%20(147).jpg"></img>
                         </div>

                    <div class="col-md-5">

                        <% end %>
     
                

                      <div class="container">

                        <div class="title">
                          <h1><%= @recipe.title %></h1>
                        </div>
                        <br/>

                         <div>
                          <h7><i class="fa fa-user-circle fa-lg" aria-hidden="true"></i>
                              By <%= @recipe.user.name %>
                          </h7>
                        </div>
                        <br />

                         <div>
                          <h7><i class="fa fa-clock-o fa-lg cyan-text" aria-hidden="true"></i>
                          <%= @recipe.preptime %>
                          </h7>
                        </div>
                        <br />

                         <div>
                          <h7><i class="fa fa-user-o fa-lg cyan-text" aria-hidden="true"></i>
                            <%= @recipe.serving %>
                          </h7>
                        </div>

                    </div>  
                  </div>

                  <div class="col"></div>

                  </div>
                  <br />
                </div>
            </div>           
           </br>

        <div class="container">
            <br />
            <div class="row">
            <br />

          <div class="col"></div>

          <div class="col-md-4">
               
            <h5>Ingredients:</h5>
            ----------------------
            <h6><%= @recipe.ingredients.map(&:name).join("<br><br>").html_safe %><h6>
                  
           </div>


        <div class="col"></div>

        <div class="col-md-7">
          <h5>Directions:</h5>
          ----------------------
          <h6><%= @recipe.prep %></h6>
        </div>

        </div>
        <br />
         <% if (signed_in? && current_user.chef) == true %>
        <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
        <%= link_to 'Delete',  @recipe,  method: :delete, data: { confirm: 'Are you sure?' } %>|
        <% end %>
        <%= link_to 'Back', recipes_path %>

        </div>

      </div>
    </div>
  </div>
</div>